language: bash
sudo: required
notifications:
  email: false
services:
  - docker
before_install:
  - mkdir .ssh
  - docker-compose -f docker-compose.yml build --build-arg environment=test travis
script:
  - docker-compose -f docker-compose.yml run travis mix deps.get
  - docker-compose -f docker-compose.yml run travis mix test
env:
  global:
    - MIX_ENV=test
